# This file was automatically generated by SWIG (https://www.swig.org).
# Version 4.2.1
#
# Do not make changes to this file unless you know what you are doing - modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
# Import the low-level C/C++ module
if __package__ or "." in __name__:
    from . import _pyebiv
else:
    import _pyebiv

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "this":
            set(self, name, value)
        elif name == "thisown":
            self.this.own(value)
        elif hasattr(self, name) and isinstance(getattr(type(self), name), property):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add instance attributes to %s" % self)
    return set_instance_attr


def _swig_setattr_nondynamic_class_variable(set):
    def set_class_attr(cls, name, value):
        if hasattr(cls, name) and not isinstance(getattr(cls, name), property):
            set(cls, name, value)
        else:
            raise AttributeError("You cannot add class attributes to %s" % cls)
    return set_class_attr


def _swig_add_metaclass(metaclass):
    """Class decorator for adding a metaclass to a SWIG wrapped class - a slimmed down version of six.add_metaclass"""
    def wrapper(cls):
        return metaclass(cls.__name__, cls.__bases__, cls.__dict__.copy())
    return wrapper


class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = _swig_setattr_nondynamic_class_variable(type.__setattr__)


class SwigPyIterator(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _pyebiv.delete_SwigPyIterator

    def value(self):
        return _pyebiv.SwigPyIterator_value(self)

    def incr(self, n=1):
        return _pyebiv.SwigPyIterator_incr(self, n)

    def decr(self, n=1):
        return _pyebiv.SwigPyIterator_decr(self, n)

    def distance(self, x):
        return _pyebiv.SwigPyIterator_distance(self, x)

    def equal(self, x):
        return _pyebiv.SwigPyIterator_equal(self, x)

    def copy(self):
        return _pyebiv.SwigPyIterator_copy(self)

    def next(self):
        return _pyebiv.SwigPyIterator_next(self)

    def __next__(self):
        return _pyebiv.SwigPyIterator___next__(self)

    def previous(self):
        return _pyebiv.SwigPyIterator_previous(self)

    def advance(self, n):
        return _pyebiv.SwigPyIterator_advance(self, n)

    def __eq__(self, x):
        return _pyebiv.SwigPyIterator___eq__(self, x)

    def __ne__(self, x):
        return _pyebiv.SwigPyIterator___ne__(self, x)

    def __iadd__(self, n):
        return _pyebiv.SwigPyIterator___iadd__(self, n)

    def __isub__(self, n):
        return _pyebiv.SwigPyIterator___isub__(self, n)

    def __add__(self, n):
        return _pyebiv.SwigPyIterator___add__(self, n)

    def __sub__(self, *args):
        return _pyebiv.SwigPyIterator___sub__(self, *args)
    def __iter__(self):
        return self

# Register SwigPyIterator in _pyebiv:
_pyebiv.SwigPyIterator_swigregister(SwigPyIterator)
class IntVector(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def iterator(self):
        return _pyebiv.IntVector_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _pyebiv.IntVector___nonzero__(self)

    def __bool__(self):
        return _pyebiv.IntVector___bool__(self)

    def __len__(self):
        return _pyebiv.IntVector___len__(self)

    def __getslice__(self, i, j):
        return _pyebiv.IntVector___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _pyebiv.IntVector___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _pyebiv.IntVector___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _pyebiv.IntVector___delitem__(self, *args)

    def __getitem__(self, *args):
        return _pyebiv.IntVector___getitem__(self, *args)

    def __setitem__(self, *args):
        return _pyebiv.IntVector___setitem__(self, *args)

    def pop(self):
        return _pyebiv.IntVector_pop(self)

    def append(self, x):
        return _pyebiv.IntVector_append(self, x)

    def empty(self):
        return _pyebiv.IntVector_empty(self)

    def size(self):
        return _pyebiv.IntVector_size(self)

    def swap(self, v):
        return _pyebiv.IntVector_swap(self, v)

    def begin(self):
        return _pyebiv.IntVector_begin(self)

    def end(self):
        return _pyebiv.IntVector_end(self)

    def rbegin(self):
        return _pyebiv.IntVector_rbegin(self)

    def rend(self):
        return _pyebiv.IntVector_rend(self)

    def clear(self):
        return _pyebiv.IntVector_clear(self)

    def get_allocator(self):
        return _pyebiv.IntVector_get_allocator(self)

    def pop_back(self):
        return _pyebiv.IntVector_pop_back(self)

    def erase(self, *args):
        return _pyebiv.IntVector_erase(self, *args)

    def __init__(self, *args):
        _pyebiv.IntVector_swiginit(self, _pyebiv.new_IntVector(*args))

    def push_back(self, x):
        return _pyebiv.IntVector_push_back(self, x)

    def front(self):
        return _pyebiv.IntVector_front(self)

    def back(self):
        return _pyebiv.IntVector_back(self)

    def assign(self, n, x):
        return _pyebiv.IntVector_assign(self, n, x)

    def resize(self, *args):
        return _pyebiv.IntVector_resize(self, *args)

    def insert(self, *args):
        return _pyebiv.IntVector_insert(self, *args)

    def reserve(self, n):
        return _pyebiv.IntVector_reserve(self, n)

    def capacity(self):
        return _pyebiv.IntVector_capacity(self)
    __swig_destroy__ = _pyebiv.delete_IntVector

# Register IntVector in _pyebiv:
_pyebiv.IntVector_swigregister(IntVector)
class DoubleVector(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def iterator(self):
        return _pyebiv.DoubleVector_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _pyebiv.DoubleVector___nonzero__(self)

    def __bool__(self):
        return _pyebiv.DoubleVector___bool__(self)

    def __len__(self):
        return _pyebiv.DoubleVector___len__(self)

    def __getslice__(self, i, j):
        return _pyebiv.DoubleVector___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _pyebiv.DoubleVector___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _pyebiv.DoubleVector___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _pyebiv.DoubleVector___delitem__(self, *args)

    def __getitem__(self, *args):
        return _pyebiv.DoubleVector___getitem__(self, *args)

    def __setitem__(self, *args):
        return _pyebiv.DoubleVector___setitem__(self, *args)

    def pop(self):
        return _pyebiv.DoubleVector_pop(self)

    def append(self, x):
        return _pyebiv.DoubleVector_append(self, x)

    def empty(self):
        return _pyebiv.DoubleVector_empty(self)

    def size(self):
        return _pyebiv.DoubleVector_size(self)

    def swap(self, v):
        return _pyebiv.DoubleVector_swap(self, v)

    def begin(self):
        return _pyebiv.DoubleVector_begin(self)

    def end(self):
        return _pyebiv.DoubleVector_end(self)

    def rbegin(self):
        return _pyebiv.DoubleVector_rbegin(self)

    def rend(self):
        return _pyebiv.DoubleVector_rend(self)

    def clear(self):
        return _pyebiv.DoubleVector_clear(self)

    def get_allocator(self):
        return _pyebiv.DoubleVector_get_allocator(self)

    def pop_back(self):
        return _pyebiv.DoubleVector_pop_back(self)

    def erase(self, *args):
        return _pyebiv.DoubleVector_erase(self, *args)

    def __init__(self, *args):
        _pyebiv.DoubleVector_swiginit(self, _pyebiv.new_DoubleVector(*args))

    def push_back(self, x):
        return _pyebiv.DoubleVector_push_back(self, x)

    def front(self):
        return _pyebiv.DoubleVector_front(self)

    def back(self):
        return _pyebiv.DoubleVector_back(self)

    def assign(self, n, x):
        return _pyebiv.DoubleVector_assign(self, n, x)

    def resize(self, *args):
        return _pyebiv.DoubleVector_resize(self, *args)

    def insert(self, *args):
        return _pyebiv.DoubleVector_insert(self, *args)

    def reserve(self, n):
        return _pyebiv.DoubleVector_reserve(self, n)

    def capacity(self):
        return _pyebiv.DoubleVector_capacity(self)
    __swig_destroy__ = _pyebiv.delete_DoubleVector

# Register DoubleVector in _pyebiv:
_pyebiv.DoubleVector_swigregister(DoubleVector)
class FloatVector(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def iterator(self):
        return _pyebiv.FloatVector_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _pyebiv.FloatVector___nonzero__(self)

    def __bool__(self):
        return _pyebiv.FloatVector___bool__(self)

    def __len__(self):
        return _pyebiv.FloatVector___len__(self)

    def __getslice__(self, i, j):
        return _pyebiv.FloatVector___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _pyebiv.FloatVector___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _pyebiv.FloatVector___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _pyebiv.FloatVector___delitem__(self, *args)

    def __getitem__(self, *args):
        return _pyebiv.FloatVector___getitem__(self, *args)

    def __setitem__(self, *args):
        return _pyebiv.FloatVector___setitem__(self, *args)

    def pop(self):
        return _pyebiv.FloatVector_pop(self)

    def append(self, x):
        return _pyebiv.FloatVector_append(self, x)

    def empty(self):
        return _pyebiv.FloatVector_empty(self)

    def size(self):
        return _pyebiv.FloatVector_size(self)

    def swap(self, v):
        return _pyebiv.FloatVector_swap(self, v)

    def begin(self):
        return _pyebiv.FloatVector_begin(self)

    def end(self):
        return _pyebiv.FloatVector_end(self)

    def rbegin(self):
        return _pyebiv.FloatVector_rbegin(self)

    def rend(self):
        return _pyebiv.FloatVector_rend(self)

    def clear(self):
        return _pyebiv.FloatVector_clear(self)

    def get_allocator(self):
        return _pyebiv.FloatVector_get_allocator(self)

    def pop_back(self):
        return _pyebiv.FloatVector_pop_back(self)

    def erase(self, *args):
        return _pyebiv.FloatVector_erase(self, *args)

    def __init__(self, *args):
        _pyebiv.FloatVector_swiginit(self, _pyebiv.new_FloatVector(*args))

    def push_back(self, x):
        return _pyebiv.FloatVector_push_back(self, x)

    def front(self):
        return _pyebiv.FloatVector_front(self)

    def back(self):
        return _pyebiv.FloatVector_back(self)

    def assign(self, n, x):
        return _pyebiv.FloatVector_assign(self, n, x)

    def resize(self, *args):
        return _pyebiv.FloatVector_resize(self, *args)

    def insert(self, *args):
        return _pyebiv.FloatVector_insert(self, *args)

    def reserve(self, n):
        return _pyebiv.FloatVector_reserve(self, n)

    def capacity(self):
        return _pyebiv.FloatVector_capacity(self)
    __swig_destroy__ = _pyebiv.delete_FloatVector

# Register FloatVector in _pyebiv:
_pyebiv.FloatVector_swigregister(FloatVector)

def SetDebugLevel(nLevel):
    return _pyebiv.SetDebugLevel(nLevel)

def DebugLevel():
    return _pyebiv.DebugLevel()
class EBIV(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    __swig_destroy__ = _pyebiv.delete_EBIV

    def __init__(self, *args):
        _pyebiv.EBIV_swiginit(self, _pyebiv.new_EBIV(*args))

    def loadRaw(self, strFileName):
        return _pyebiv.EBIV_loadRaw(self, strFileName)

    def save(self, strFileName, t0=0, duration=0):
        return _pyebiv.EBIV_save(self, strFileName, t0, duration)

    def width(self):
        return _pyebiv.EBIV_width(self)

    def height(self):
        return _pyebiv.EBIV_height(self)

    def isNull(self):
        return _pyebiv.EBIV_isNull(self)

    def eventCount(self):
        return _pyebiv.EBIV_eventCount(self)

    def timeStamp(self):
        return _pyebiv.EBIV_timeStamp(self)

    def sensorSize(self):
        return _pyebiv.EBIV_sensorSize(self)

    def events(self):
        return _pyebiv.EBIV_events(self)

    def time(self):
        return _pyebiv.EBIV_time(self)

    def x(self):
        return _pyebiv.EBIV_x(self)

    def y(self):
        return _pyebiv.EBIV_y(self)

    def p(self):
        return _pyebiv.EBIV_p(self)

    def pseudoImage(self, t0_usec, duration, polarity):
        return _pyebiv.EBIV_pseudoImage(self, t0_usec, duration, polarity)

    def estimatePulseOffsetTime(self, freqInHz, nBinWidthInMicrosec, nPeriods, nStartPeriod):
        return _pyebiv.EBIV_estimatePulseOffsetTime(self, freqInHz, nBinWidthInMicrosec, nPeriods, nStartPeriod)

    def meanPulseHistogram(self, freqInHz, nBinWidthInMicrosec, nPeriods, nStartPeriod):
        return _pyebiv.EBIV_meanPulseHistogram(self, freqInHz, nBinWidthInMicrosec, nPeriods, nStartPeriod)

    def setDebugLevel(self, nLevel):
        return _pyebiv.EBIV_setDebugLevel(self, nLevel)

# Register EBIV in _pyebiv:
_pyebiv.EBIV_swigregister(EBIV)

